Repository skim-rs/skim, pull requests merged in 2024-11, with the labels that each got.

#551 remove -K and -R flags from tmux popup: uknown flags
  bin/sk-tmux
Labels: bug, tmux

#563 ansi parser: fix dim / half-bright
  src/ansi.rs
Labels: tui

#587 chore: remove atty
  Cargo.lock
  Cargo.toml
  src/bin/main.rs
Labels: bug, dependencies

#579 chore: remove bitflags
  Cargo.lock
  Cargo.toml
  src/bin/main.rs
  src/engine/fuzzy.rs
  src/event.rs
  src/header.rs
  src/previewer.rs
  src/query.rs
  src/selection.rs
  src/util.rs
Labels: dependencies

#468 Return items of multi-select in order of selection
  Cargo.lock
  Cargo.toml
  examples/custom_keybinding_actions.rs
  src/selection.rs
  test/test_skim.py
Labels: enhancement, dependencies

#586 feat: use clap & derive for options, manpage & completions
  .cargo/config.toml
  Cargo.lock
  Cargo.toml
  man/man1/sk.1
  shell/completion.bash
  shell/completion.zsh
  skim/Cargo.toml
  skim/examples/custom_item.rs
  skim/examples/custom_keybinding_actions.rs
  skim/examples/downcast.rs
  skim/examples/nth.rs
  skim/examples/option_builder.rs
  skim/examples/sample.rs
  skim/src/ansi.rs
  skim/src/bin/main.rs
  skim/src/context.rs
  skim/src/engine/all.rs
  skim/src/engine/andor.rs
  skim/src/engine/exact.rs
  skim/src/engine/factory.rs
  skim/src/engine/fuzzy.rs
  skim/src/engine/mod.rs
  skim/src/engine/regexp.rs
  skim/src/engine/util.rs
  skim/src/event.rs
  skim/src/field.rs
  skim/src/global.rs
  skim/src/header.rs
  skim/src/helper/item.rs
  skim/src/helper/item_reader.rs
  skim/src/helper/mod.rs
  skim/src/helper/selector.rs
  skim/src/input.rs
  skim/src/item.rs
  skim/src/lib.rs
  skim/src/matcher.rs
  skim/src/model.rs
  skim/src/options.rs
  skim/src/orderedvec.rs
  skim/src/output.rs
  skim/src/prelude.rs
  skim/src/previewer.rs
  skim/src/query.rs
  skim/src/reader.rs
  skim/src/selection.rs
  skim/src/spinlock.rs
  skim/src/theme.rs
  skim/src/util.rs
  src/bin/main.rs
  src/options.rs
  test/test_skim.py
  xtask/Cargo.toml
  xtask/src/main.rs
Labels: enhancement, dependencies

#613 feat: allow more flexibility for use as a library
  skim/examples/cmd_collector.rs
  skim/examples/selector.rs
  skim/src/bin/main.rs
  skim/src/context.rs
  skim/src/lib.rs
  skim/src/options.rs
  skim/src/query.rs
  skim/src/reader.rs
  skim/src/selection.rs
Labels: lib

#609 feat: readd index tiebreak
  man/man1/sk.1
  shell/completion.bash
  shell/completion.zsh
  skim/examples/downcast.rs
  skim/src/engine/all.rs
  skim/src/engine/exact.rs
  skim/src/engine/fuzzy.rs
  skim/src/engine/regexp.rs
  skim/src/helper/item.rs
  skim/src/helper/item_reader.rs
  skim/src/item.rs
  skim/src/lib.rs
  skim/src/matcher.rs
  skim/src/model.rs
  test/test_skim.py
Labels: enhancement

#625 feat!: do not check for expect before printing the argument of accept…
  skim/src/bin/main.rs
  skim/src/options.rs
  test/run.sh
  test/test_skim.py
Labels: skip-title-check

#603 feat: add `--tmux` flag (deprecates sk-tmux, fixes #596)
  Cargo.lock
  README.md
  bin/sk-tmux
  skim/Cargo.toml
  skim/src/bin/main.rs
  skim/src/lib.rs
  skim/src/options.rs
  skim/src/tmux.rs
  test/mock.sh
  test/run.sh
  test/test_skim.py
Labels: tmux

#630 feat(tui): add info hidden
  e2e/tests/options.rs
  man/man1/sk.1
  shell/completion.bash
  shell/completion.zsh
  skim/src/model/mod.rs
  skim/src/model/options.rs
  skim/src/model/status.rs
  skim/src/options.rs
  xtask/src/main.rs
Labels: enhancement, feature-request, tui
